name: CI

on:
  pull_request:
  merge_group:

env:
    python-version: 3.11.4

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python ${{ env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}

    - name: Activate the cache for pip
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: venv
        key: pip-v3-python-${{ env.python-version }}-${{ hashFiles('requirements-dev.lock') }}
        restore-keys: |
            pip-v3-python-${{ env.python-version }}-${{ hashFiles('requirements-dev.lock') }}
            pip-v3-python-${{ env.python-version }}-

    - name: Setup venv
      if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
      run: |
        python3 -m venv venv
        venv/bin/pip install pip-tools

    - name: Install Python dependencies
      run: make sync

    - name: Run tests
      run: make tests

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python ${{ env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}

    - name: Activate the cache for pip
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: venv
        key: pip-v3-python-${{ env.python-version }}-${{ hashFiles('requirements-dev.lock') }}
        restore-keys: |
            pip-v3-python-${{ env.python-version }}-${{ hashFiles('requirements-dev.lock') }}
            pip-v3-python-${{ env.python-version }}-

    - name: Activate the cache for pre-commit
      uses: actions/cache@v3
      with:
        path: /tmp/pre-commit-cache
        key: pre-commit-v7-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
            pre-commit-v7-

    - name: Setup venv
      if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
      run: |
        python3 -m venv venv
        venv/bin/pip install pip-tools

    - name: Install Python dependencies
      run: make sync

    - name: pre-commit
      run: ./venv/bin/pre-commit run --all-files
      env:
        PRE_COMMIT_HOME: /tmp/pre-commit-cache
