name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
    python-version: 3.11.3

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python ${{ env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}

    - name: Activate the cache for pip
      uses: actions/cache@v3
      with:
        path: .venv
        key: pip-v3-python-${{ env.python-version }}-${{ hashFiles('requirements-dev.lock') }}
        restore-keys: |
            pip-v3-python-${{ env.python-version }}-${{ hashFiles('requirements-dev.lock') }}
            pip-v3-python-${{ env.python-version }}-

    - name: Activate the cache for pre-commit
      uses: actions/cache@v3
      with:
        path: /tmp/pre-commit-cache
        key: pre-commit-v7-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
            pre-commit-v7-

    - uses: eifinger/setup-rye@v1

    - name: Install rye and Python dependencies
      run: |
        rye sync

    - name: pre-commit
      run: ./venv/bin/pre-commit run --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
      env:
        PRE_COMMIT_HOME: /tmp/pre-commit-cache
